//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassAct2
{
    using System;
    using System.Collections.Generic;
    
    public partial class lgsalary_history
    {
        public decimal emp_num { get; set; }
        public Nullable<System.DateTime> sal_from { get; set; }
        public Nullable<System.DateTime> sal_end { get; set; }
        public Nullable<decimal> sal_amount { get; set; }
    }
}
